sudo: false
language: python
python:
  - python: "3.6"
  - python: "3.6-dev"
  - python: "nightly"
allow_failures:
  - python: "3.6-dev" # 3.6 development branch
  - python: "nightly" # currently points to 3.7-dev
install:
  - pip install coveralls
  - python setup.py install
script:
  coverage run --source=. setup.py test

after_success:
  - coveralls
